<Project>
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Erik Barale</Authors>
		<Copyright>Copyright (c) 2026 Erik Barale</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>Icon.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/berik-99/FluentLocalizer</RepositoryUrl>
		<PackageProjectUrl>https://github.com/berik-99/FluentLocalizer</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
		<IsPackable>true</IsPackable>
		<PackageOutputPath>bin\$(Configuration)\Packages\</PackageOutputPath>
	</PropertyGroup>

	<ItemGroup>

		<None Include="Assets\README.md"
			  Pack="true"
			  PackagePath="\" />

		<None Include="Assets\LICENSE"
			  Pack="true"
			  PackagePath="\" />

		<None Include="Assets\Icon.png"
			  Pack="true"
			  PackagePath="\" />

	</ItemGroup>


</Project>