<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>FluentLocalizer</PackageId>
		<Product>FluentLocalizer</Product>
		<RootNamespace>FluentLocalizer</RootNamespace>
		<Version>0.0.1</Version>
		<Description>
			Core library for building culture-aware translation pipelines in .NET with fluent APIs, MessageFormat-style interpolation, and configurable fallback and error handling.
		</Description>
		<PackageTags>localization;translation;messageformat;culture;fluent;dotnet</PackageTags>
		<GenerateDependencyFile>false</GenerateDependencyFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessageFormat" Version="8.0.0" />
	</ItemGroup>


	<ItemGroup>
		<Folder Include="Enums\" FolderSameAsRootNamespace="false" />
	</ItemGroup>


	<Import Project="..\FluentLocalizer.Shared.Polyfill\FluentLocalizer.Shared.Polyfill.projitems" Label="Shared" />

</Project>
